/**
 * Built-in theme presets.
 *
 * Each theme provides both light and dark color sets.
 * Reader colors are optional — if absent, derived from the main color set.
 */
import { DEFAULT_STYLE, type ThemeDefinition } from "./theme-schema";

// ─── Default (current light/dark) ────────────────────────────────────────────

const defaultTheme: ThemeDefinition = {
  id: "default",
  name: "默认",
  nameEn: "Default",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#faf9f5",
    foreground: "#1c1c1e",
    card: "#ffffff",
    cardForeground: "#1c1c1e",
    primary: "#2d2d30",
    primaryForeground: "#fafafa",
    secondary: "#f5f5f5",
    secondaryForeground: "#2d2d30",
    muted: "#f2f1ed",
    mutedForeground: "#7c7c82",
    accent: "#f5f5f5",
    accentForeground: "#2d2d30",
    destructive: "#e53935",
    destructiveForeground: "#fafafa",
    border: "#e5e5e5",
    input: "#e5e5e5",
    ring: "#a3a3a3",
    sidebar: "#fafafa",
    sidebarForeground: "#1c1c1e",
    popover: "#ffffff",
    popoverForeground: "#1c1c1e",
  },
  dark: {
    background: "#121212",
    foreground: "#f5f5f5",
    card: "#1e1e1e",
    cardForeground: "#f5f5f5",
    primary: "#ffffff",
    primaryForeground: "#121212",
    secondary: "#2a2a2a",
    secondaryForeground: "#ffffff",
    muted: "#2a2a2a",
    mutedForeground: "#a0a0a0",
    accent: "#2a2a2a",
    accentForeground: "#ffffff",
    destructive: "#e53935",
    destructiveForeground: "#ffffff",
    border: "#333333",
    input: "#333333",
    ring: "#6366f1",
    sidebar: "#1a1a1a",
    sidebarForeground: "#f5f5f5",
    popover: "#1e1e1e",
    popoverForeground: "#f5f5f5",
  },
  reader: {
    light: { background: "#ffffff", foreground: "#1a1a1a", linkColor: "#2563eb" },
    dark: { background: "#121212", foreground: "#f5f5f5", linkColor: "#60a5fa" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Sepia (warm paper / eye comfort) ────────────────────────────────────────

const sepiaTheme: ThemeDefinition = {
  id: "sepia",
  name: "暖纸",
  nameEn: "Warm Paper",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#f0e6d2",
    foreground: "#3d2b1f",
    card: "#f5ebd7",
    cardForeground: "#3d2b1f",
    primary: "#6b4c2a",
    primaryForeground: "#f5ebd7",
    secondary: "#e6d9c3",
    secondaryForeground: "#4a3728",
    muted: "#e6d9c3",
    mutedForeground: "#7a6652",
    accent: "#e6d9c3",
    accentForeground: "#4a3728",
    destructive: "#e53935",
    destructiveForeground: "#fafafa",
    border: "#d4c4a8",
    input: "#d4c4a8",
    ring: "#6b4c2a",
    sidebar: "#f5ebd7",
    sidebarForeground: "#3d2b1f",
    popover: "#f5ebd7",
    popoverForeground: "#3d2b1f",
  },
  dark: {
    background: "#1a1410",
    foreground: "#e8dcc8",
    card: "#221c14",
    cardForeground: "#e8dcc8",
    primary: "#d4a574",
    primaryForeground: "#1a1410",
    secondary: "#2a2018",
    secondaryForeground: "#e8dcc8",
    muted: "#2a2018",
    mutedForeground: "#a89878",
    accent: "#2a2018",
    accentForeground: "#e8dcc8",
    destructive: "#e53935",
    destructiveForeground: "#ffffff",
    border: "#3a2e20",
    input: "#3a2e20",
    ring: "#d4a574",
    sidebar: "#1e1812",
    sidebarForeground: "#e8dcc8",
    popover: "#221c14",
    popoverForeground: "#e8dcc8",
  },
  reader: {
    light: { background: "#f0e6d2", foreground: "#3d2b1f", linkColor: "#6b4c2a" },
    dark: { background: "#1a1410", foreground: "#e8dcc8", linkColor: "#d4a574" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Nord ────────────────────────────────────────────────────────────────────

const nordTheme: ThemeDefinition = {
  id: "nord",
  name: "北欧",
  nameEn: "Nord",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#eceff4",
    foreground: "#2e3440",
    card: "#ffffff",
    cardForeground: "#2e3440",
    primary: "#5e81ac",
    primaryForeground: "#eceff4",
    secondary: "#e5e9f0",
    secondaryForeground: "#2e3440",
    muted: "#e5e9f0",
    mutedForeground: "#4c566a",
    accent: "#d8dee9",
    accentForeground: "#2e3440",
    destructive: "#bf616a",
    destructiveForeground: "#eceff4",
    border: "#d8dee9",
    input: "#d8dee9",
    ring: "#5e81ac",
    sidebar: "#e5e9f0",
    sidebarForeground: "#2e3440",
    popover: "#ffffff",
    popoverForeground: "#2e3440",
  },
  dark: {
    background: "#2e3440",
    foreground: "#eceff4",
    card: "#3b4252",
    cardForeground: "#eceff4",
    primary: "#88c0d0",
    primaryForeground: "#2e3440",
    secondary: "#3b4252",
    secondaryForeground: "#eceff4",
    muted: "#3b4252",
    mutedForeground: "#d8dee9",
    accent: "#434c5e",
    accentForeground: "#eceff4",
    destructive: "#bf616a",
    destructiveForeground: "#eceff4",
    border: "#434c5e",
    input: "#434c5e",
    ring: "#88c0d0",
    sidebar: "#3b4252",
    sidebarForeground: "#eceff4",
    popover: "#3b4252",
    popoverForeground: "#eceff4",
  },
  reader: {
    light: { background: "#eceff4", foreground: "#2e3440", linkColor: "#5e81ac" },
    dark: { background: "#2e3440", foreground: "#d8dee9", linkColor: "#88c0d0" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Paper (minimal, no color) ───────────────────────────────────────────────

const paperTheme: ThemeDefinition = {
  id: "paper",
  name: "纯净",
  nameEn: "Paper",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#ffffff",
    foreground: "#111111",
    card: "#fafafa",
    cardForeground: "#111111",
    primary: "#111111",
    primaryForeground: "#ffffff",
    secondary: "#f5f5f5",
    secondaryForeground: "#111111",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#f5f5f5",
    accentForeground: "#111111",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    ring: "#a3a3a3",
    sidebar: "#fafafa",
    sidebarForeground: "#111111",
    popover: "#ffffff",
    popoverForeground: "#111111",
  },
  dark: {
    background: "#0a0a0a",
    foreground: "#fafafa",
    card: "#141414",
    cardForeground: "#fafafa",
    primary: "#fafafa",
    primaryForeground: "#0a0a0a",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#1a1a1a",
    mutedForeground: "#a3a3a3",
    accent: "#1a1a1a",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#fafafa",
    border: "#262626",
    input: "#262626",
    ring: "#525252",
    sidebar: "#0f0f0f",
    sidebarForeground: "#fafafa",
    popover: "#141414",
    popoverForeground: "#fafafa",
  },
  style: { ...DEFAULT_STYLE, shadowLevel: "none", borderStyle: "subtle" },
};

// ─── Ocean ───────────────────────────────────────────────────────────────────

const oceanTheme: ThemeDefinition = {
  id: "ocean",
  name: "深海",
  nameEn: "Ocean",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#f0f7ff",
    foreground: "#1e3a5f",
    card: "#ffffff",
    cardForeground: "#1e3a5f",
    primary: "#0ea5e9",
    primaryForeground: "#ffffff",
    secondary: "#e0f2fe",
    secondaryForeground: "#1e3a5f",
    muted: "#e0f2fe",
    mutedForeground: "#4a7196",
    accent: "#e0f2fe",
    accentForeground: "#1e3a5f",
    destructive: "#e53935",
    destructiveForeground: "#ffffff",
    border: "#bae6fd",
    input: "#bae6fd",
    ring: "#0ea5e9",
    sidebar: "#e0f2fe",
    sidebarForeground: "#1e3a5f",
    popover: "#ffffff",
    popoverForeground: "#1e3a5f",
  },
  dark: {
    background: "#0c1929",
    foreground: "#e0f2fe",
    card: "#132f4c",
    cardForeground: "#e0f2fe",
    primary: "#38bdf8",
    primaryForeground: "#0c1929",
    secondary: "#1e3a5f",
    secondaryForeground: "#e0f2fe",
    muted: "#1e3a5f",
    mutedForeground: "#7dd3fc",
    accent: "#1e3a5f",
    accentForeground: "#e0f2fe",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e3a5f",
    input: "#1e3a5f",
    ring: "#38bdf8",
    sidebar: "#0f2137",
    sidebarForeground: "#e0f2fe",
    popover: "#132f4c",
    popoverForeground: "#e0f2fe",
  },
  reader: {
    light: { background: "#f0f7ff", foreground: "#1e3a5f", linkColor: "#0ea5e9" },
    dark: { background: "#0c1929", foreground: "#e0f2fe", linkColor: "#38bdf8" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Rosé Pine ───────────────────────────────────────────────────────────────

const rosePineTheme: ThemeDefinition = {
  id: "rosepine",
  name: "玫瑰松",
  nameEn: "Rosé Pine",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#faf4ed",
    foreground: "#575279",
    card: "#fffaf3",
    cardForeground: "#575279",
    primary: "#907aa9",
    primaryForeground: "#faf4ed",
    secondary: "#f2e9e1",
    secondaryForeground: "#575279",
    muted: "#f2e9e1",
    mutedForeground: "#797593",
    accent: "#f2e9e1",
    accentForeground: "#575279",
    destructive: "#b4637a",
    destructiveForeground: "#faf4ed",
    border: "#dfdad9",
    input: "#dfdad9",
    ring: "#907aa9",
    sidebar: "#f2e9e1",
    sidebarForeground: "#575279",
    popover: "#fffaf3",
    popoverForeground: "#575279",
  },
  dark: {
    background: "#191724",
    foreground: "#e0def4",
    card: "#1f1d2e",
    cardForeground: "#e0def4",
    primary: "#c4a7e7",
    primaryForeground: "#191724",
    secondary: "#26233a",
    secondaryForeground: "#e0def4",
    muted: "#26233a",
    mutedForeground: "#908caa",
    accent: "#26233a",
    accentForeground: "#e0def4",
    destructive: "#eb6f92",
    destructiveForeground: "#191724",
    border: "#393552",
    input: "#393552",
    ring: "#c4a7e7",
    sidebar: "#1f1d2e",
    sidebarForeground: "#e0def4",
    popover: "#1f1d2e",
    popoverForeground: "#e0def4",
  },
  reader: {
    light: { background: "#faf4ed", foreground: "#575279", linkColor: "#907aa9" },
    dark: { background: "#191724", foreground: "#e0def4", linkColor: "#c4a7e7" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Dracula ─────────────────────────────────────────────────────────────────

const draculaTheme: ThemeDefinition = {
  id: "dracula",
  name: "德古拉",
  nameEn: "Dracula",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#f8f8f2",
    foreground: "#282a36",
    card: "#ffffff",
    cardForeground: "#282a36",
    primary: "#6272a4",
    primaryForeground: "#f8f8f2",
    secondary: "#f1f1e8",
    secondaryForeground: "#282a36",
    muted: "#f1f1e8",
    mutedForeground: "#6272a4",
    accent: "#f1f1e8",
    accentForeground: "#282a36",
    destructive: "#ff5555",
    destructiveForeground: "#f8f8f2",
    border: "#e0e0d8",
    input: "#e0e0d8",
    ring: "#6272a4",
    sidebar: "#f1f1e8",
    sidebarForeground: "#282a36",
    popover: "#ffffff",
    popoverForeground: "#282a36",
  },
  dark: {
    background: "#282a36",
    foreground: "#f8f8f2",
    card: "#343746",
    cardForeground: "#f8f8f2",
    primary: "#bd93f9",
    primaryForeground: "#282a36",
    secondary: "#44475a",
    secondaryForeground: "#f8f8f2",
    muted: "#44475a",
    mutedForeground: "#6272a4",
    accent: "#44475a",
    accentForeground: "#f8f8f2",
    destructive: "#ff5555",
    destructiveForeground: "#f8f8f2",
    border: "#44475a",
    input: "#44475a",
    ring: "#bd93f9",
    sidebar: "#21222c",
    sidebarForeground: "#f8f8f2",
    popover: "#343746",
    popoverForeground: "#f8f8f2",
  },
  reader: {
    light: { background: "#f8f8f2", foreground: "#282a36", linkColor: "#6272a4" },
    dark: { background: "#282a36", foreground: "#f8f8f2", linkColor: "#8be9fd" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Forest ──────────────────────────────────────────────────────────────────

const forestTheme: ThemeDefinition = {
  id: "forest",
  name: "森林",
  nameEn: "Forest",
  builtIn: true,
  createdAt: 0,
  updatedAt: 0,
  light: {
    background: "#f2f7f2",
    foreground: "#1a2e1a",
    card: "#ffffff",
    cardForeground: "#1a2e1a",
    primary: "#2d6a4f",
    primaryForeground: "#f2f7f2",
    secondary: "#e6f0e6",
    secondaryForeground: "#1a2e1a",
    muted: "#e6f0e6",
    mutedForeground: "#4a7a5a",
    accent: "#e6f0e6",
    accentForeground: "#1a2e1a",
    destructive: "#e53935",
    destructiveForeground: "#ffffff",
    border: "#c8e0c8",
    input: "#c8e0c8",
    ring: "#2d6a4f",
    sidebar: "#e6f0e6",
    sidebarForeground: "#1a2e1a",
    popover: "#ffffff",
    popoverForeground: "#1a2e1a",
  },
  dark: {
    background: "#0d1f0d",
    foreground: "#d4e8d4",
    card: "#162816",
    cardForeground: "#d4e8d4",
    primary: "#52b788",
    primaryForeground: "#0d1f0d",
    secondary: "#1b3a1b",
    secondaryForeground: "#d4e8d4",
    muted: "#1b3a1b",
    mutedForeground: "#81c995",
    accent: "#1b3a1b",
    accentForeground: "#d4e8d4",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1b3a1b",
    input: "#1b3a1b",
    ring: "#52b788",
    sidebar: "#0f240f",
    sidebarForeground: "#d4e8d4",
    popover: "#162816",
    popoverForeground: "#d4e8d4",
  },
  reader: {
    light: { background: "#f2f7f2", foreground: "#1a2e1a", linkColor: "#2d6a4f" },
    dark: { background: "#0d1f0d", foreground: "#d4e8d4", linkColor: "#52b788" },
  },
  style: { ...DEFAULT_STYLE },
};

// ─── Exports ─────────────────────────────────────────────────────────────────

export const BUILTIN_THEMES: ThemeDefinition[] = [
  defaultTheme,
  sepiaTheme,
  nordTheme,
  paperTheme,
  oceanTheme,
  forestTheme,
  rosePineTheme,
  draculaTheme,
];

export function getBuiltinTheme(id: string): ThemeDefinition | undefined {
  return BUILTIN_THEMES.find((t) => t.id === id);
}

export function getDefaultTheme(): ThemeDefinition {
  return defaultTheme;
}
